# Generated by Django 3.1.1 on 2020-10-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AreasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('slept_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AreasApp.area')),
            ],
            options={
                'db_table': 'worker',
            },
        ),
    ]
