# Generated by Django 3.1.1 on 2020-10-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fatigue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slept_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time_to_bed', models.DateTimeField(blank=True)),
                ('time_to_wake', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'fatigue',
            },
        ),
    ]
