# Generated by Django 3.1.1 on 2020-10-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
