# Generated by Django 3.1.1 on 2020-10-22 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0002_excel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'carga',
            },
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contratista',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'destino',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='ModalidadIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'modalidad_ingreso',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'motivo',
            },
        ),
        migrations.CreateModel(
            name='NumConvoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'num_convoy',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tipo_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'transporte',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa1', models.CharField(max_length=200)),
                ('placa2', models.CharField(max_length=200)),
                ('apellidos_nombres', models.CharField(max_length=200)),
                ('num_licencia', models.CharField(max_length=200)),
                ('relevo_apellidos_nombres', models.CharField(max_length=200)),
                ('relevo_licencia', models.CharField(max_length=200)),
                ('relevo_placa1', models.CharField(max_length=200)),
                ('relevo_placa2', models.CharField(max_length=200)),
                ('telefono_escolta', models.CharField(max_length=200)),
                ('telefono_satelital', models.CharField(max_length=200)),
                ('num_guia', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_llegada', models.CharField(max_length=200)),
                ('hora_llegada', models.CharField(max_length=200)),
                ('eta_site', models.CharField(max_length=200)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.carga')),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.contratista')),
                ('desde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desde', to='ExcelApp.destino')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.estado')),
                ('excel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.excel')),
                ('hacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hacia', to='ExcelApp.destino')),
                ('modalidad_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.modalidadingreso')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.motivo')),
                ('num_convoy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.numconvoy')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.tipovehiculo')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.transporte')),
            ],
            options={
                'db_table': 'programacion_general',
            },
        ),
    ]
