# Generated by Django 3.1.1 on 2020-10-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0003_carga_contratista_destino_estado_modalidadingreso_motivo_numconvoy_programaciongeneral_tipovehiculo_'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaciongeneral',
            name='ea',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
