# Generated by Django 3.1.1 on 2020-10-22 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0004_programaciongeneral_ea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaciongeneral',
            name='apellidos_nombres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.carga'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='contratista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.contratista'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='desde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='desde', to='ExcelApp.destino'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.estado'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='eta_site',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='excel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.excel'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='fecha_llegada',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='hacia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hacia', to='ExcelApp.destino'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='hora_llegada',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='modalidad_ingreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.modalidadingreso'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='motivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.motivo'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='num_convoy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.numconvoy'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='num_guia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='num_licencia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='placa1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='placa2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='relevo_apellidos_nombres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='relevo_licencia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='relevo_placa1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='relevo_placa2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='telefono_escolta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='tipo_vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.tipovehiculo'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='transporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.transporte'),
        ),
    ]
