# Generated by Django 3.1.1 on 2020-10-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0005_auto_20201021_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaciongeneral',
            name='telefono_satelital',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
