# Generated by Django 3.1.1 on 2020-10-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0006_auto_20201021_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaciongeneral',
            name='hora_partida',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='programaciongeneral',
            name='pasajeros',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
