# Generated by Django 3.1.1 on 2020-10-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0007_auto_20201022_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='state',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
