# Generated by Django 3.1.1 on 2020-10-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0008_excel_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'conductor',
            },
        ),
        migrations.RemoveField(
            model_name='programaciongeneral',
            name='apellidos_nombres',
        ),
        migrations.RemoveField(
            model_name='programaciongeneral',
            name='num_licencia',
        ),
        migrations.RemoveField(
            model_name='programaciongeneral',
            name='relevo_apellidos_nombres',
        ),
        migrations.RemoveField(
            model_name='programaciongeneral',
            name='relevo_licencia',
        ),
        migrations.AddField(
            model_name='programaciongeneral',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conductor', to='ExcelApp.conductor'),
        ),
        migrations.AddField(
            model_name='programaciongeneral',
            name='conductor_reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conductor_reserva', to='ExcelApp.conductor'),
        ),
    ]
