# Generated by Django 3.1.1 on 2020-10-29 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0009_auto_20201029_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaciongeneral',
            name='conductor_reserva',
        ),
        migrations.AddField(
            model_name='programaciongeneral',
            name='conductor_relevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conductor_relevo', to='ExcelApp.conductor'),
        ),
    ]
