# Generated by Django 3.1.1 on 2020-10-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0011_auto_20201029_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorArchivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatiga_file', models.CharField(max_length=200)),
                ('declaracion_file', models.CharField(max_length=200)),
                ('iperc_file', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelApp.contratista')),
            ],
            options={
                'db_table': 'conductor_archivos',
            },
        ),
    ]
