# Generated by Django 3.1.1 on 2020-10-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0012_conductorarchivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductorarchivos',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelApp.conductor'),
        ),
    ]
