# Generated by Django 3.1.1 on 2020-10-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0013_auto_20201030_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductorarchivos',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
