# Generated by Django 3.1.1 on 2020-10-30 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0014_auto_20201030_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion_plan', models.CharField(max_length=200, null=True)),
                ('programacion_general_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.programaciongeneral')),
            ],
            options={
                'db_table': 'observaciones',
            },
        ),
    ]
