# Generated by Django 3.1.1 on 2020-11-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0016_auto_20201101_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='observaciones',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
