# Generated by Django 3.1.1 on 2020-11-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0018_auto_20201105_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaArchivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_file', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=10)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExcelApp.placa')),
            ],
            options={
                'db_table': 'placa_archivos',
            },
        ),
    ]
