# Generated by Django 3.1.1 on 2020-11-12 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0019_placaarchivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lugar',
            },
        ),
        migrations.AddField(
            model_name='observaciones',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ExcelApp.lugar'),
        ),
    ]
