# Generated by Django 3.1.1 on 2020-12-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0020_auto_20201112_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorarchivos',
            name='declaracion_file_encode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='conductorarchivos',
            name='fatiga_file_encode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='conductorarchivos',
            name='iperc_file_encode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='evidencia_correctiva_encode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='evidencia_encode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='placaarchivos',
            name='checklist_file_encode',
            field=models.TextField(null=True),
        ),
    ]
