# Generated by Django 3.1.1 on 2021-01-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0023_auto_20201207_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='placaarchivos',
            name='photo1_encode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='placaarchivos',
            name='photo2_encode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='placaarchivos',
            name='photo3_encode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='placaarchivos',
            name='photo4_encode',
            field=models.TextField(null=True),
        ),
    ]
