# Generated by Django 3.1.1 on 2021-01-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0024_auto_20210114_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaciongeneral',
            name='cantidad_desinfectado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='programaciongeneral',
            name='comentario',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
