# Generated by Django 3.1.1 on 2021-01-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelApp', '0025_auto_20210114_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='programacion_general_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExcelApp.programaciongeneral'),
        ),
        migrations.AlterField(
            model_name='programaciongeneral',
            name='excel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExcelApp.excel'),
        ),
        migrations.CreateModel(
            name='FotosObservaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia_encode', models.TextField(null=True)),
                ('evidencia_correctiva_encode', models.TextField(null=True)),
                ('obervacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExcelApp.observaciones')),
            ],
            options={
                'db_table': 'fotos_observaciones',
            },
        ),
    ]
