# Generated by Django 3.1.1 on 2020-10-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
